// Blooptopia 3D — Achievements
// Each: { id, name, desc, icon, tier:'bronze'|'silver'|'gold', coins, check(stats) }
// coins by tier: bronze 10–25, silver 30–75, gold 80–200.
// check is a PURE function of the stats object (see docs/SPEC.md "Stats object").

export const achievements = [
  // ── Levels completed ──────────────────────────────────────────────
  {
    id: 'first-roll',
    name: 'First Roll',
    desc: 'Complete your very first level.',
    icon: '🎳',
    tier: 'bronze',
    coins: 10,
    check: (s) => s.levelsCompleted >= 1,
  },
  {
    id: 'getting-rolling',
    name: 'Getting Rolling',
    desc: 'Complete 10 levels.',
    icon: '🎢',
    tier: 'bronze',
    coins: 20,
    check: (s) => s.levelsCompleted >= 10,
  },
  {
    id: 'quarter-blooped',
    name: 'Quarter Blooped',
    desc: 'Complete 25 levels.',
    icon: '🛼',
    tier: 'silver',
    coins: 45,
    check: (s) => s.levelsCompleted >= 25,
  },
  {
    id: 'forty-and-bloopy',
    name: 'Forty & Bloopy',
    desc: 'Complete 40 levels.',
    icon: '🏔️',
    tier: 'silver',
    coins: 65,
    check: (s) => s.levelsCompleted >= 40,
  },
  {
    id: 'grand-tour',
    name: 'Grand Tour',
    desc: 'Complete all 60 levels of Blooptopia.',
    icon: '🗺️',
    tier: 'gold',
    coins: 150,
    check: (s) => s.levelsCompleted >= 60,
  },

  // ── Star milestones ───────────────────────────────────────────────
  {
    id: 'star-struck',
    name: 'Star Struck',
    desc: 'Collect 10 stars.',
    icon: '⭐',
    tier: 'bronze',
    coins: 15,
    check: (s) => s.totalStars >= 10,
  },
  {
    id: 'starter-pack',
    name: 'Starter Pack',
    desc: 'Collect 30 stars.',
    icon: '✨',
    tier: 'bronze',
    coins: 25,
    check: (s) => s.totalStars >= 30,
  },
  {
    id: 'sixty-sparkles',
    name: 'Sixty Sparkles',
    desc: 'Collect 60 stars.',
    icon: '🌟',
    tier: 'silver',
    coins: 45,
    check: (s) => s.totalStars >= 60,
  },
  {
    id: 'century-of-shine',
    name: 'Century of Shine',
    desc: 'Collect 100 stars.',
    icon: '💫',
    tier: 'silver',
    coins: 70,
    check: (s) => s.totalStars >= 100,
  },
  {
    id: 'stellar-scholar',
    name: 'Stellar Scholar',
    desc: 'Collect 150 stars.',
    icon: '🌠',
    tier: 'gold',
    coins: 110,
    check: (s) => s.totalStars >= 150,
  },
  {
    id: 'full-constellation',
    name: 'Full Constellation',
    desc: 'Collect every single star — all 180!',
    icon: '🌌',
    tier: 'gold',
    coins: 200,
    check: (s) => s.totalStars >= 180,
  },

  // ── Perfect levels ────────────────────────────────────────────────
  {
    id: 'first-perfection',
    name: 'First Perfection',
    desc: 'Beat a level perfectly — 3 stars and under par.',
    icon: '🎯',
    tier: 'bronze',
    coins: 20,
    check: (s) => s.perfectLevels >= 1,
  },
  {
    id: 'perfect-ten',
    name: 'Perfect Ten',
    desc: 'Get a perfect clear on 10 levels.',
    icon: '🏅',
    tier: 'silver',
    coins: 55,
    check: (s) => s.perfectLevels >= 10,
  },
  {
    id: 'thirty-flawless',
    name: 'Thirty Flawless',
    desc: 'Get a perfect clear on 30 levels.',
    icon: '💠',
    tier: 'gold',
    coins: 100,
    check: (s) => s.perfectLevels >= 30,
  },
  {
    id: 'flawless-bloop',
    name: 'Flawless Bloop',
    desc: 'Perfect-clear every level in the game.',
    icon: '👑',
    tier: 'gold',
    coins: 200,
    check: (s) => s.perfectLevels >= 60,
  },

  // ── Each world completed ──────────────────────────────────────────
  {
    id: 'meadow-mapper',
    name: 'Meadow Mapper',
    desc: 'Finish every level of Bloopberry Meadows.',
    icon: '🌼',
    tier: 'silver',
    coins: 40,
    check: (s) => s.worldsCompleted[0] === true,
  },
  {
    id: 'cavern-crawler',
    name: 'Cavern Crawler',
    desc: 'Finish every level of Crystal Caverns.',
    icon: '💎',
    tier: 'silver',
    coins: 45,
    check: (s) => s.worldsCompleted[1] === true,
  },
  {
    id: 'canyon-conqueror',
    name: 'Canyon Conqueror',
    desc: 'Finish every level of Loopy Canyon.',
    icon: '🏜️',
    tier: 'silver',
    coins: 50,
    check: (s) => s.worldsCompleted[2] === true,
  },
  {
    id: 'junction-jumper',
    name: 'Junction Jumper',
    desc: 'Finish every level of Function Junction.',
    icon: '🚦',
    tier: 'silver',
    coins: 55,
    check: (s) => s.worldsCompleted[3] === true,
  },
  {
    id: 'peak-performer',
    name: 'Peak Performer',
    desc: 'Finish every level of Bugstorm Peaks.',
    icon: '⛰️',
    tier: 'gold',
    coins: 90,
    check: (s) => s.worldsCompleted[4] === true,
  },

  // ── Each world perfected ──────────────────────────────────────────
  {
    id: 'meadow-master',
    name: 'Meadow Master',
    desc: 'Three-star every level in Bloopberry Meadows.',
    icon: '🌻',
    tier: 'gold',
    coins: 85,
    check: (s) => s.worldsPerfected[0] === true,
  },
  {
    id: 'crystal-clear',
    name: 'Crystal Clear',
    desc: 'Three-star every level in Crystal Caverns.',
    icon: '🔮',
    tier: 'gold',
    coins: 90,
    check: (s) => s.worldsPerfected[1] === true,
  },
  {
    id: 'loop-legend',
    name: 'Loop Legend',
    desc: 'Three-star every level in Loopy Canyon.',
    icon: '🌀',
    tier: 'gold',
    coins: 95,
    check: (s) => s.worldsPerfected[2] === true,
  },
  {
    id: 'function-fanatic',
    name: 'Function Fanatic',
    desc: 'Three-star every level in Function Junction.',
    icon: '🧩',
    tier: 'gold',
    coins: 100,
    check: (s) => s.worldsPerfected[3] === true,
  },
  {
    id: 'storm-slayer',
    name: 'Storm Slayer',
    desc: 'Three-star every level in Bugstorm Peaks.',
    icon: '⚡',
    tier: 'gold',
    coins: 150,
    check: (s) => s.worldsPerfected[4] === true,
  },

  // ── Coins earned ──────────────────────────────────────────────────
  {
    id: 'piggy-bank',
    name: 'Piggy Bank',
    desc: 'Earn 100 coins in total.',
    icon: '🐷',
    tier: 'bronze',
    coins: 15,
    check: (s) => s.coinsEarned >= 100,
  },
  {
    id: 'coin-collector',
    name: 'Coin Collector',
    desc: 'Earn 500 coins in total.',
    icon: '🪙',
    tier: 'silver',
    coins: 40,
    check: (s) => s.coinsEarned >= 500,
  },
  {
    id: 'bloop-fortune',
    name: 'Bloop Fortune',
    desc: 'Earn 1,000 coins in total.',
    icon: '💰',
    tier: 'silver',
    coins: 70,
    check: (s) => s.coinsEarned >= 1000,
  },
  {
    id: 'gazillionaire',
    name: 'Gazillionaire',
    desc: 'Earn 5,000 coins in total.',
    icon: '🤑',
    tier: 'gold',
    coins: 150,
    check: (s) => s.coinsEarned >= 5000,
  },

  // ── Coins spent ───────────────────────────────────────────────────
  {
    id: 'window-shopper',
    name: 'Window Shopper',
    desc: 'Spend 50 coins in the shop.',
    icon: '🛍️',
    tier: 'bronze',
    coins: 15,
    check: (s) => s.coinsSpent >= 50,
  },
  {
    id: 'big-spender',
    name: 'Big Spender',
    desc: 'Spend 500 coins in the shop.',
    icon: '🛒',
    tier: 'silver',
    coins: 45,
    check: (s) => s.coinsSpent >= 500,
  },
  {
    id: 'shop-till-you-drop',
    name: 'Shop Till You Drop',
    desc: 'Spend 2,000 coins in the shop.',
    icon: '💳',
    tier: 'gold',
    coins: 120,
    check: (s) => s.coinsSpent >= 2000,
  },

  // ── Runs ──────────────────────────────────────────────────────────
  {
    id: 'test-pilot',
    name: 'Test Pilot',
    desc: 'Run your program 10 times.',
    icon: '🕹️',
    tier: 'bronze',
    coins: 12,
    check: (s) => s.runs >= 10,
  },
  {
    id: 'press-play',
    name: 'Press Play',
    desc: 'Run your program 50 times.',
    icon: '▶️',
    tier: 'silver',
    coins: 35,
    check: (s) => s.runs >= 50,
  },
  {
    id: 'run-runner',
    name: 'Run Runner',
    desc: 'Run your program 200 times.',
    icon: '🏃',
    tier: 'gold',
    coins: 90,
    check: (s) => s.runs >= 200,
  },

  // ── Fails (keep-trying fun) ───────────────────────────────────────
  {
    id: 'oops-a-daisy',
    name: 'Oops-a-Daisy',
    desc: 'Take a tumble 10 times. It happens!',
    icon: '🙈',
    tier: 'bronze',
    coins: 12,
    check: (s) => s.fails >= 10,
  },
  {
    id: 'bug-hunter',
    name: 'Bug Hunter',
    desc: 'Fail 25 runs — every bug you squash makes you smarter.',
    icon: '🐛',
    tier: 'bronze',
    coins: 20,
    check: (s) => s.fails >= 25,
  },
  {
    id: 'never-give-up',
    name: 'Never Give Up',
    desc: 'Fail 100 runs and keep on rolling.',
    icon: '💪',
    tier: 'silver',
    coins: 45,
    check: (s) => s.fails >= 100,
  },

  // ── Commands used ─────────────────────────────────────────────────
  {
    id: 'command-cadet',
    name: 'Command Cadet',
    desc: 'Execute 100 direction commands.',
    icon: '🎮',
    tier: 'bronze',
    coins: 15,
    check: (s) => s.commandsUsed >= 100,
  },
  {
    id: 'command-captain',
    name: 'Command Captain',
    desc: 'Execute 1,000 direction commands.',
    icon: '🧭',
    tier: 'silver',
    coins: 50,
    check: (s) => s.commandsUsed >= 1000,
  },
  {
    id: 'command-commander',
    name: 'Command Commander',
    desc: 'Execute 5,000 direction commands.',
    icon: '🎖️',
    tier: 'gold',
    coins: 120,
    check: (s) => s.commandsUsed >= 5000,
  },

  // ── Loops used ────────────────────────────────────────────────────
  {
    id: 'loop-there-it-is',
    name: 'Loop There It Is',
    desc: 'Run 10 loop blocks.',
    icon: '🔁',
    tier: 'bronze',
    coins: 18,
    check: (s) => s.loopsUsed >= 10,
  },
  {
    id: 'in-the-loop',
    name: 'In The Loop',
    desc: 'Run 50 loop blocks.',
    icon: '🔄',
    tier: 'silver',
    coins: 45,
    check: (s) => s.loopsUsed >= 50,
  },
  {
    id: 'loop-de-loop',
    name: 'Loop-de-Loop',
    desc: 'Run 100 loop blocks.',
    icon: '➰',
    tier: 'gold',
    coins: 100,
    check: (s) => s.loopsUsed >= 100,
  },

  // ── Function calls ────────────────────────────────────────────────
  {
    id: 'function-over-form',
    name: 'Function Over Form',
    desc: 'Call function F1 10 times.',
    icon: '📞',
    tier: 'bronze',
    coins: 18,
    check: (s) => s.functionCalls >= 10,
  },
  {
    id: 'call-me-maybe',
    name: 'Call Me Maybe',
    desc: 'Call function F1 50 times.',
    icon: '☎️',
    tier: 'silver',
    coins: 45,
    check: (s) => s.functionCalls >= 50,
  },
  {
    id: 'function-junkie',
    name: 'Function Junkie',
    desc: 'Call function F1 100 times.',
    icon: '🧠',
    tier: 'gold',
    coins: 100,
    check: (s) => s.functionCalls >= 100,
  },

  // ── Conditions fired ──────────────────────────────────────────────
  {
    id: 'color-me-curious',
    name: 'Color Me Curious',
    desc: 'Trigger 10 color conditions.',
    icon: '🎨',
    tier: 'bronze',
    coins: 18,
    check: (s) => s.conditionsFired >= 10,
  },
  {
    id: 'condition-critical',
    name: 'Condition Critical',
    desc: 'Trigger 50 color conditions.',
    icon: '🚥',
    tier: 'silver',
    coins: 45,
    check: (s) => s.conditionsFired >= 50,
  },
  {
    id: 'reflex-master',
    name: 'Reflex Master',
    desc: 'Trigger 100 color conditions.',
    icon: '🌈',
    tier: 'gold',
    coins: 100,
    check: (s) => s.conditionsFired >= 100,
  },

  // ── Characters owned ──────────────────────────────────────────────
  {
    id: 'dynamic-duo',
    name: 'Dynamic Duo',
    desc: 'Own 2 bloopy characters.',
    icon: '👯',
    tier: 'bronze',
    coins: 15,
    check: (s) => s.charactersOwned >= 2,
  },
  {
    id: 'bloop-squad',
    name: 'Bloop Squad',
    desc: 'Own 5 bloopy characters.',
    icon: '🧸',
    tier: 'silver',
    coins: 40,
    check: (s) => s.charactersOwned >= 5,
  },
  {
    id: 'bloop-family',
    name: 'Bloop Family',
    desc: 'Own 10 bloopy characters.',
    icon: '👨‍👩‍👧‍👦',
    tier: 'silver',
    coins: 65,
    check: (s) => s.charactersOwned >= 10,
  },
  {
    id: 'gotta-bloop-em-all',
    name: "Gotta Bloop 'Em All",
    desc: 'Own all 16 bloopy characters.',
    icon: '🎪',
    tier: 'gold',
    coins: 160,
    check: (s) => s.charactersOwned >= 16,
  },

  // ── First-try wins ────────────────────────────────────────────────
  {
    id: 'nailed-it',
    name: 'Nailed It',
    desc: 'Beat a level on your very first run.',
    icon: '🔨',
    tier: 'bronze',
    coins: 20,
    check: (s) => s.firstTryWins >= 1,
  },
  {
    id: 'one-and-done',
    name: 'One and Done',
    desc: 'Win 10 levels on the first try.',
    icon: '🥇',
    tier: 'silver',
    coins: 50,
    check: (s) => s.firstTryWins >= 10,
  },
  {
    id: 'first-try-phenom',
    name: 'First-Try Phenom',
    desc: 'Win 25 levels on the first try.',
    icon: '🎓',
    tier: 'gold',
    coins: 95,
    check: (s) => s.firstTryWins >= 25,
  },
  {
    id: 'planner-supreme',
    name: 'Planner Supreme',
    desc: 'Win 50 levels on the first try.',
    icon: '🔭',
    tier: 'gold',
    coins: 160,
    check: (s) => s.firstTryWins >= 50,
  },

  // ── No-fail streak ────────────────────────────────────────────────
  {
    id: 'hot-streak',
    name: 'Hot Streak',
    desc: 'Win 5 runs in a row without a fail.',
    icon: '🔥',
    tier: 'bronze',
    coins: 22,
    check: (s) => s.noFailStreakBest >= 5,
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    desc: 'Win 10 runs in a row without a fail.',
    icon: '🚀',
    tier: 'silver',
    coins: 55,
    check: (s) => s.noFailStreakBest >= 10,
  },
  {
    id: 'flawless-frenzy',
    name: 'Flawless Frenzy',
    desc: 'Win 20 runs in a row without a fail.',
    icon: '🏆',
    tier: 'gold',
    coins: 130,
    check: (s) => s.noFailStreakBest >= 20,
  },

  // ── Lifetime stars collected (roll-over count) ────────────────────
  {
    id: 'stardust-gatherer',
    name: 'Stardust Gatherer',
    desc: 'Roll over 100 stars across all your runs.',
    icon: '🌟',
    tier: 'silver',
    coins: 40,
    check: (s) => s.starsCollectedLifetime >= 100,
  },
  {
    id: 'stardust-hoarder',
    name: 'Stardust Hoarder',
    desc: 'Roll over 500 stars across all your runs.',
    icon: '☄️',
    tier: 'gold',
    coins: 110,
    check: (s) => s.starsCollectedLifetime >= 500,
  },
];
