// Blooptopia 3D — playable character roster.
// 16 bloops, unlocked with coins. First one (Blip) is free.
export const characters = [
  {
    id: 'blip',
    name: 'Blip',
    desc: 'The original bloop who just loves to roll in a straight, happy line.',
    cost: 0,
    colors: { body: '#5db4ff', accent: '#1e5fa8' },
    accessory: 'none',
    eyes: 'round',
    trail: '#a6d8ff',
  },
  {
    id: 'sunny',
    name: 'Sunny',
    desc: 'A giggly ball of sunshine who thinks every maze is a beach day.',
    cost: 50,
    colors: { body: '#ffe14d', accent: '#d69e00' },
    accessory: 'cap',
    eyes: 'happy',
    trail: '#fff08a',
  },
  {
    id: 'rosie',
    name: 'Rosie',
    desc: 'A bubblegum sweetie who winks at every star she scoops up.',
    cost: 75,
    colors: { body: '#ff86b0', accent: '#c94472' },
    accessory: 'bow',
    eyes: 'wink',
    trail: '#ffb8d3',
  },
  {
    id: 'mossy',
    name: 'Mossy',
    desc: 'A cheerful little sprout who leaves a garden wherever he bounces.',
    cost: 100,
    colors: { body: '#57c06a', accent: '#2b7a44' },
    accessory: 'flower',
    eyes: 'happy',
    trail: '#9fe3ac',
  },
  {
    id: 'tangelo',
    name: 'Tangelo',
    desc: 'A zippy citrus bloop whose wobbly antennae sniff out every coin.',
    cost: 150,
    colors: { body: '#ff7a2f', accent: '#c14e10' },
    accessory: 'antennae',
    eyes: 'round',
    trail: '#ffab6b',
  },
  {
    id: 'grape',
    name: 'Grape',
    desc: 'A dreamy purple thinker who solves mazes with sleepy, clever eyes.',
    cost: 200,
    colors: { body: '#9b5de5', accent: '#6a34b0' },
    accessory: 'glasses',
    eyes: 'sleepy',
    trail: '#c39bf2',
  },
  {
    id: 'minty',
    name: 'Minty',
    desc: 'A breezy mint bloop who rolls to the beat in her cozy headphones.',
    cost: 250,
    colors: { body: '#63dcc8', accent: '#279e88' },
    accessory: 'headphones',
    eyes: 'happy',
    trail: '#a8f0e4',
  },
  {
    id: 'coral',
    name: 'Coral',
    desc: 'A feisty red rascal with tiny horns and a big grumpy grin.',
    cost: 300,
    colors: { body: '#ff5c5c', accent: '#c02020' },
    accessory: 'horns',
    eyes: 'angry',
    trail: '#ff9a9a',
  },
  {
    id: 'lumen',
    name: 'Lumen',
    desc: 'A gentle pastel angel who floats through loops with a glowing halo.',
    cost: 400,
    colors: { body: '#c9b6f0', accent: '#8a6fc4' },
    accessory: 'halo',
    eyes: 'sleepy',
    trail: '#e4d8fa',
  },
  {
    id: 'zapp',
    name: 'Zapp',
    desc: 'A crackling neon speedster whose spiky quills buzz with electricity.',
    cost: 500,
    colors: { body: '#adff2f', accent: '#6fa600' },
    accessory: 'spikes',
    eyes: 'angry',
    trail: '#d0ff85',
  },
  {
    id: 'bubbles',
    name: 'Bubbles',
    desc: 'A hot-magenta prankster who wiggles her antennae and never stops winking.',
    cost: 600,
    colors: { body: '#ff33a8', accent: '#b10068' },
    accessory: 'antennae',
    eyes: 'wink',
    trail: '#ff8fcf',
  },
  {
    id: 'frostbyte',
    name: 'Frostbyte',
    desc: 'An icy-cool coder who reads the maze twice through frosty spectacles.',
    cost: 700,
    colors: { body: '#7fe9ff', accent: '#2ba0c4' },
    accessory: 'glasses',
    eyes: 'round',
    trail: '#bff4ff',
  },
  {
    id: 'emberling',
    name: 'Emberling',
    desc: 'A smoldering crimson daredevil with fiery horns and a fearless scowl.',
    cost: 800,
    colors: { body: '#d72638', accent: '#7a0f1c' },
    accessory: 'horns',
    eyes: 'angry',
    trail: '#ff5e6c',
  },
  {
    id: 'seraph',
    name: 'Seraph',
    desc: 'A shimmering star-eyed guardian who drifts through mazes on a golden halo.',
    cost: 950,
    colors: { body: '#f3eede', accent: '#cbb26b' },
    accessory: 'halo',
    eyes: 'star',
    trail: '#fffbe8',
  },
  {
    id: 'shadowpaw',
    name: 'Shadowpaw',
    desc: 'A silent ninja bloop who slips through the trickiest paths with a sly wink.',
    cost: 1100,
    colors: { body: '#3a3f5c', accent: '#14172b' },
    accessory: 'ninja',
    eyes: 'wink',
    trail: '#6d74a3',
  },
  {
    id: 'regalia',
    name: 'Regalia',
    desc: 'The legendary golden ruler of Blooptopia, crowned with cosmic star eyes.',
    cost: 1200,
    colors: { body: '#e8b923', accent: '#a67c00' },
    accessory: 'crown',
    eyes: 'star',
    trail: '#ffd75e',
  },
];
