// World 5 — Bugstorm Peaks
// MASTERY: conditions + loops + functions combined. The hardest 12 levels.
// Every level's `solution` wins with all 3 stars; validate.js proves it.
const D = (d) => ({ t: 'dir', d });
const R = D('R'), L = D('L'), U = D('U'), Dn = D('D');
const C = { t: 'call', f: 0 };
const Lp = (n, body) => ({ t: 'loop', n, body });

export const levels = [
  {
    id: 'w5-01', world: 5, index: 1,
    name: 'Storm Steps',
    intro: 'Loop the staircase, then let the pink tile sweep you into the exit.',
    grid: [
      'S##      ',
      '  #      ',
      '  *#c    ',
      '    #    ',
      '    *#c  ',
      '      #  ',
      '    E*p  ',
    ],
    allowed: { dirs: ['R', 'D', 'L'], loops: true, functions: false, conditions: ['p'], maxMain: 2 },
    parCommands: 1,
    solution: { main: [Lp(3, [R, Dn])], functions: [], conditions: [{ color: 'p', d: 'L' }] },
  },
  {
    id: 'w5-02', world: 5, index: 2,
    name: 'Left-Hand Peak',
    intro: 'One function walks each step. A pink tile at the bottom turns you to the door.',
    grid: [
      '    #*S',
      '    #  ',
      '  c#*  ',
      '  #    ',
      'p*#E   ',
    ],
    allowed: { dirs: ['L', 'D', 'R'], loops: false, functions: true, conditions: ['p'], maxMain: 4 },
    parCommands: 3,
    solution: { main: [C, C, C], functions: [[L, Dn]], conditions: [{ color: 'p', d: 'R' }] },
  },
  {
    id: 'w5-03', world: 5, index: 3,
    name: 'Two Trails',
    intro: 'Loop the first descent, then a function does the switchback to the exit.',
    grid: [
      'S*#      ',
      '  #      ',
      '  *#c    ',
      '    #    ',
      '#*###    ',
      '#        ',
      'E        ',
    ],
    allowed: { dirs: ['R', 'D', 'L'], loops: true, functions: true, conditions: [], maxMain: 3 },
    parCommands: 2,
    solution: { main: [Lp(2, [R, Dn]), C], functions: [[L, Dn]], conditions: [] },
  },
  {
    id: 'w5-04', world: 5, index: 4,
    name: 'Down the Gorge',
    intro: 'Loop down-and-right. The orange tile flips you right into the door.',
    grid: [
      'S      ',
      'c      ',
      '*##    ',
      '  c    ',
      '  *##  ',
      '    #  ',
      '    o*E',
    ],
    allowed: { dirs: ['D', 'R'], loops: true, functions: false, conditions: ['o'], maxMain: 2 },
    parCommands: 1,
    solution: { main: [Lp(3, [Dn, R])], functions: [], conditions: [{ color: 'o', d: 'R' }] },
  },
  {
    id: 'w5-05', world: 5, index: 5,
    name: 'Serpent Pass',
    intro: 'Bind three colors and a single Right threads the whole snake — then call to finish.',
    grid: [
      'S*#p  ',
      '   #  ',
      'p*#o  ',
      '#     ',
      'g##*  ',
      '   #  ',
      '   E  ',
    ],
    allowed: { dirs: ['R', 'D', 'L'], loops: false, functions: true, conditions: ['p', 'o', 'g'], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, C], functions: [[Dn]], conditions: [{ color: 'p', d: 'D' }, { color: 'o', d: 'L' }, { color: 'g', d: 'R' }] },
  },
  {
    id: 'w5-06', world: 5, index: 6,
    name: 'Twin Ridges',
    intro: 'Loop the left-hand climb down, then a function crosses to the exit.',
    grid: [
      '    #*S',
      '    #  ',
      '  c#*  ',
      '  #    ',
      '  ##*# ',
      '     # ',
      '     E ',
    ],
    allowed: { dirs: ['L', 'D', 'R'], loops: true, functions: true, conditions: [], maxMain: 3 },
    parCommands: 2,
    solution: { main: [Lp(2, [L, Dn]), C], functions: [[R, Dn]], conditions: [] },
  },
  {
    id: 'w5-07', world: 5, index: 7,
    name: 'Everything Storm',
    intro: 'All three tools: loop the steps, call the run, and a pink tile drops you home.',
    grid: [
      'S##      ',
      '  #      ',
      '  *#c    ',
      '    #    ',
      '    *#*p ',
      '       # ',
      '       E ',
    ],
    allowed: { dirs: ['R', 'D'], loops: true, functions: true, conditions: ['p'], maxMain: 3 },
    parCommands: 2,
    solution: { main: [Lp(2, [R, Dn]), C], functions: [[R]], conditions: [{ color: 'p', d: 'D' }] },
  },
  {
    id: 'w5-08', world: 5, index: 8,
    name: 'The Long Fall',
    intro: 'One loop, four steps. At the very bottom the blue tile turns you to the exit.',
    grid: [
      'S##        ',
      '  #        ',
      '  *#c      ',
      '    #      ',
      '    c#c    ',
      '      #    ',
      '      *#c  ',
      '        #  ',
      '      E*b  ',
    ],
    allowed: { dirs: ['R', 'D', 'L'], loops: true, functions: false, conditions: ['b'], maxMain: 2 },
    parCommands: 1,
    solution: { main: [Lp(4, [R, Dn])], functions: [], conditions: [{ color: 'b', d: 'L' }] },
  },
  {
    id: 'w5-09', world: 5, index: 9,
    name: 'Coil Canyon',
    intro: 'Two colors coil the path; one Right rides it, then call the finish.',
    grid: [
      'S*#p    ',
      '   #    ',
      'p*#o    ',
      '#       ',
      '###*    ',
      '   #    ',
      '   E    ',
    ],
    allowed: { dirs: ['R', 'D', 'L'], loops: false, functions: true, conditions: ['p', 'o'], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, C], functions: [[R, Dn]], conditions: [{ color: 'p', d: 'D' }, { color: 'o', d: 'L' }] },
  },
  {
    id: 'w5-10', world: 5, index: 10,
    name: 'Cliffhanger',
    intro: 'Loop three big steps, then one function makes the final long switchback.',
    grid: [
      'S##       ',
      '  #       ',
      '  *#c     ',
      '    #     ',
      '    *#c   ',
      '      #   ',
      '#*#####   ',
      '#         ',
      'E         ',
    ],
    allowed: { dirs: ['R', 'D', 'L'], loops: true, functions: true, conditions: [], maxMain: 3 },
    parCommands: 2,
    solution: { main: [Lp(3, [R, Dn]), C], functions: [[L, Dn]], conditions: [] },
  },
  {
    id: 'w5-11', world: 5, index: 11,
    name: 'Bug Vortex',
    intro: 'Two commands only: loop the whole staircase, then call a run that the orange tile drops home.',
    grid: [
      'S##       ',
      '  #       ',
      '  *#c     ',
      '    #     ',
      '    c#c   ',
      '      #   ',
      '      *#*o',
      '         #',
      '         E',
    ],
    allowed: { dirs: ['R', 'D'], loops: true, functions: true, conditions: ['o'], maxMain: 2 },
    parCommands: 2,
    solution: { main: [Lp(3, [R, Dn]), C], functions: [[R]], conditions: [{ color: 'o', d: 'D' }] },
  },
  {
    id: 'w5-12', world: 5, index: 12,
    name: 'Peak of the Storm',
    intro: 'The final climb: loop the great staircase, call the run, and two colors snake you to the summit door.',
    grid: [
      'S##         ',
      '  #         ',
      '  *#c       ',
      '    #       ',
      '    *#c     ',
      '      #     ',
      '      #*#p  ',
      '         #  ',
      '      E##g  ',
    ],
    allowed: { dirs: ['R', 'D', 'L'], loops: true, functions: true, conditions: ['p', 'g'], maxMain: 3 },
    parCommands: 2,
    solution: { main: [Lp(3, [R, Dn]), C], functions: [[R]], conditions: [{ color: 'p', d: 'D' }, { color: 'g', d: 'L' }] },
  },
];
