// WORLD 2 — Crystal Caverns
// Introduces COLOR CONDITIONS. A condition {color, d} redirects Bloop every time
// it ENTERS a matching-color tile. Early: one pink condition. Later: 2-3 colors,
// tiles reused so one condition fires several times.

const U = { t: 'dir', d: 'U' };
const D = { t: 'dir', d: 'D' };
const L = { t: 'dir', d: 'L' };
const R = { t: 'dir', d: 'R' };

export const levels = [
  {
    id: 'w2-01',
    world: 2,
    index: 1,
    name: 'Pink Turn',
    intro: 'Bind PINK to DOWN. When Bloop hits a pink crystal, it turns by itself!',
    grid: ['S#p', '  *', '  *', '  *', '  E'],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: ['p'], maxMain: 2 },
    parCommands: 1,
    solution: { main: [R], functions: [], conditions: [{ color: 'p', d: 'D' }] },
  },
  {
    id: 'w2-02',
    world: 2,
    index: 2,
    name: 'Pink Then Go',
    intro: 'Pink turns Bloop down. You still add the last move to reach the exit.',
    grid: ['S#p', '  *', '  *', 'E#*'],
    allowed: { dirs: ['R', 'L'], loops: false, functions: false, conditions: ['p'], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, L], functions: [], conditions: [{ color: 'p', d: 'D' }] },
  },
  {
    id: 'w2-03',
    world: 2,
    index: 3,
    name: 'Pink Again',
    intro: 'One pink rule fires at EVERY pink crystal. Reuse it!',
    grid: ['S#p  ', '  *  ', '  *#p', '    *', '    E'],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: ['p'], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, R], functions: [], conditions: [{ color: 'p', d: 'D' }] },
  },
  {
    id: 'w2-04',
    world: 2,
    index: 4,
    name: 'Blue Crystal',
    intro: 'New color: BLUE. Bind pink and blue to different turns.',
    grid: ['S#p   ', '  *   ', '  b**E'],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: ['p', 'b'], maxMain: 2 },
    parCommands: 1,
    solution: { main: [R], functions: [], conditions: [{ color: 'p', d: 'D' }, { color: 'b', d: 'R' }] },
  },
  {
    id: 'w2-05',
    world: 2,
    index: 5,
    name: 'Cavern Crossing',
    intro: 'Pink fires twice, blue once. One command rides the whole path.',
    grid: ['S#p  ', '  *  ', '  b*p', '    *', '    E'],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: ['p', 'b'], maxMain: 2 },
    parCommands: 1,
    solution: { main: [R], functions: [], conditions: [{ color: 'p', d: 'D' }, { color: 'b', d: 'R' }] },
  },
  {
    id: 'w2-06',
    world: 2,
    index: 6,
    name: 'Green Grotto',
    intro: 'Three colors make a full loop around the grotto. Grab the coin!',
    grid: ['S#*p E', '   c *', '   * #', '   b#g'],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: ['p', 'b', 'g'], maxMain: 2 },
    parCommands: 1,
    solution: {
      main: [R],
      functions: [],
      conditions: [{ color: 'p', d: 'D' }, { color: 'b', d: 'R' }, { color: 'g', d: 'U' }],
    },
  },
  {
    id: 'w2-07',
    world: 2,
    index: 7,
    name: 'Detour Diamond',
    intro: 'Colors do some turns, you do the rest. Mix them together.',
    grid: ['S#*#p', '    #', '##*#b', '*    ', 'E    '],
    allowed: { dirs: ['R', 'D'], loops: false, functions: false, conditions: ['p', 'b'], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, D], functions: [], conditions: [{ color: 'p', d: 'D' }, { color: 'b', d: 'L' }] },
  },
  {
    id: 'w2-08',
    world: 2,
    index: 8,
    name: 'Repeat Offender',
    intro: 'The same pink rule fires three times to build a staircase.',
    grid: ['S*p    ', '  #*p  ', '    #*p', '      E'],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: ['p'], maxMain: 4 },
    parCommands: 3,
    solution: { main: [R, R, R], functions: [], conditions: [{ color: 'p', d: 'D' }] },
  },
  {
    id: 'w2-09',
    world: 2,
    index: 9,
    name: 'Crystal Circuit',
    intro: 'Pink, blue, green — one push sends Bloop all the way around.',
    grid: ['S#*#p', 'E   #', '#   *', 'g#*#b'],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: ['p', 'b', 'g'], maxMain: 2 },
    parCommands: 1,
    solution: {
      main: [R],
      functions: [],
      conditions: [{ color: 'p', d: 'D' }, { color: 'b', d: 'L' }, { color: 'g', d: 'U' }],
    },
  },
  {
    id: 'w2-10',
    world: 2,
    index: 10,
    name: 'Orange Arrival',
    intro: 'Meet ORANGE. Colors carry Bloop across, you nudge it between.',
    grid: ['S#*##p', '     c', '#####b', '*     ', 'o##*#E'],
    allowed: { dirs: ['R', 'D'], loops: false, functions: false, conditions: ['p', 'b', 'o'], maxMain: 3 },
    parCommands: 2,
    solution: {
      main: [R, D],
      functions: [],
      conditions: [{ color: 'p', d: 'D' }, { color: 'b', d: 'L' }, { color: 'o', d: 'R' }],
    },
  },
  {
    id: 'w2-11',
    world: 2,
    index: 11,
    name: 'Pink Puzzle',
    intro: 'Pink fires twice here. Think about where each turn lands you.',
    grid: ['S     E', '*     #', 'p#*#  *', '   #  #', '   p##b'],
    allowed: { dirs: ['D'], loops: false, functions: false, conditions: ['p', 'b'], maxMain: 3 },
    parCommands: 2,
    solution: { main: [D, D], functions: [], conditions: [{ color: 'p', d: 'R' }, { color: 'b', d: 'U' }] },
  },
  {
    id: 'w2-12',
    world: 2,
    index: 12,
    name: 'Crystal Master',
    intro: 'The finale: three colors, pink twice. Plan the whole crystal run.',
    grid: ['S#*#p ', '    # ', 'g#*#b ', '#     ', '#*#p  ', '   E  '],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: ['p', 'b', 'g'], maxMain: 3 },
    parCommands: 2,
    solution: {
      main: [R, R],
      functions: [],
      conditions: [{ color: 'p', d: 'D' }, { color: 'b', d: 'L' }, { color: 'g', d: 'D' }],
    },
  },
];
