// WORLD 1 — Bloopberry Meadows
// Pure sequences: direction commands only. No loops, functions, or conditions.
// Teaches R first, then D, U, L, ramping to windy multi-turn mazes.

const U = { t: 'dir', d: 'U' };
const D = { t: 'dir', d: 'D' };
const L = { t: 'dir', d: 'L' };
const R = { t: 'dir', d: 'R' };

export const levels = [
  {
    id: 'w1-01',
    world: 1,
    index: 1,
    name: 'First Roll',
    intro: 'Tap RIGHT to send Bloop rolling. It grabs stars along the way!',
    grid: ['S***E'],
    allowed: { dirs: ['R'], loops: false, functions: false, conditions: [], maxMain: 3 },
    parCommands: 1,
    solution: { main: [R], functions: [], conditions: [] },
  },
  {
    id: 'w1-02',
    world: 1,
    index: 2,
    name: 'Downhill',
    intro: 'Bloop can roll DOWN too. One command carries it all the way.',
    grid: ['S', '*', '*', '*', 'E'],
    allowed: { dirs: ['D'], loops: false, functions: false, conditions: [], maxMain: 3 },
    parCommands: 1,
    solution: { main: [D], functions: [], conditions: [] },
  },
  {
    id: 'w1-03',
    world: 1,
    index: 3,
    name: 'Around the Bend',
    intro: 'Roll RIGHT, then turn DOWN. Two commands make a corner.',
    grid: ['S#*', '  *', '  *', '  E'],
    allowed: { dirs: ['R', 'D'], loops: false, functions: false, conditions: [], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, D], functions: [], conditions: [] },
  },
  {
    id: 'w1-04',
    world: 1,
    index: 4,
    name: 'Step Down',
    intro: 'Bloop rolls until it hits the edge, then waits for the next command.',
    grid: ['S#*  ', '  *  ', '  *#E'],
    allowed: { dirs: ['R', 'D'], loops: false, functions: false, conditions: [], maxMain: 4 },
    parCommands: 3,
    solution: { main: [R, D, R], functions: [], conditions: [] },
  },
  {
    id: 'w1-05',
    world: 1,
    index: 5,
    name: 'Take a Left',
    intro: 'New move: LEFT. Coins are a fun bonus — grab them if you can!',
    grid: ['S##*#', '    c', 'E#*#*'],
    allowed: { dirs: ['R', 'D', 'L'], loops: false, functions: false, conditions: [], maxMain: 4 },
    parCommands: 3,
    solution: { main: [R, D, L], functions: [], conditions: [] },
  },
  {
    id: 'w1-06',
    world: 1,
    index: 6,
    name: 'Look Up',
    intro: 'Now try UP. Plan the loop around the meadow: down, across, up.',
    grid: ['S   E', '*   #', '#   *', '#c*##'],
    allowed: { dirs: ['U', 'D', 'R'], loops: false, functions: false, conditions: [], maxMain: 4 },
    parCommands: 3,
    solution: { main: [D, R, U], functions: [], conditions: [] },
  },
  {
    id: 'w1-07',
    world: 1,
    index: 7,
    name: 'Staircase',
    intro: 'Right, down, right, down — like walking down steps.',
    grid: ['S#*  ', '  c  ', '  ##*', '    *', '    E'],
    allowed: { dirs: ['R', 'D'], loops: false, functions: false, conditions: [], maxMain: 5 },
    parCommands: 4,
    solution: { main: [R, D, R, D], functions: [], conditions: [] },
  },
  {
    id: 'w1-08',
    world: 1,
    index: 8,
    name: 'Zigzag',
    intro: 'Watch the walls — Bloop stops when the path runs out.',
    grid: ['S###*', '##*##', '*    ', 'E    '],
    allowed: { dirs: ['R', 'D', 'L'], loops: false, functions: false, conditions: [], maxMain: 5 },
    parCommands: 4,
    solution: { main: [R, D, L, D], functions: [], conditions: [] },
  },
  {
    id: 'w1-09',
    world: 1,
    index: 9,
    name: 'Big Steps',
    intro: 'A longer staircase. Follow the path one corner at a time.',
    grid: ['S#*    ', '  #    ', '  ##*  ', '    #  ', '    *#E'],
    allowed: { dirs: ['R', 'D'], loops: false, functions: false, conditions: [], maxMain: 6 },
    parCommands: 5,
    solution: { main: [R, D, R, D, R], functions: [], conditions: [] },
  },
  {
    id: 'w1-10',
    world: 1,
    index: 10,
    name: 'The Long Way',
    intro: 'This trail doubles back. Trace it with your finger first!',
    grid: ['S##*', '#*##', '#   ', '#c##', '   *', '   E'],
    allowed: { dirs: ['R', 'D', 'L'], loops: false, functions: false, conditions: [], maxMain: 7 },
    parCommands: 6,
    solution: { main: [R, D, L, D, R, D], functions: [], conditions: [] },
  },
  {
    id: 'w1-11',
    world: 1,
    index: 11,
    name: 'Windy Trail',
    intro: 'A snaking path — plan every turn before you run it.',
    grid: ['S##*', '   #', '#*##', '#   ', '####', '   #', 'E#*#'],
    allowed: { dirs: ['R', 'D', 'L'], loops: false, functions: false, conditions: [], maxMain: 8 },
    parCommands: 7,
    solution: { main: [R, D, L, D, R, D, L], functions: [], conditions: [] },
  },
  {
    id: 'w1-12',
    world: 1,
    index: 12,
    name: 'Grand Meadow Maze',
    intro: 'The big finish! Eight commands wind all the way to the exit.',
    grid: ['S##*', '   #', '#c##', '#   ', '#*##', '   #', '##*#', 'E   '],
    allowed: { dirs: ['R', 'D', 'L'], loops: false, functions: false, conditions: [], maxMain: 9 },
    parCommands: 8,
    solution: { main: [R, D, L, D, R, D, L, D], functions: [], conditions: [] },
  },
];
