// WORLD 3 — Loopy Canyon
// Introduces LOOPS: {t:'loop', n, body:[dir tokens]}. The body repeats n times.
// Early: one loop of a 2-step body. Late: loop + extra commands with tight
// maxMain budgets that FORCE the loop.

const U = { t: 'dir', d: 'U' };
const D = { t: 'dir', d: 'D' };
const L = { t: 'dir', d: 'L' };
const R = { t: 'dir', d: 'R' };
const loop = (n, ...body) => ({ t: 'loop', n, body });

export const levels = [
  {
    id: 'w3-01',
    world: 3,
    index: 1,
    name: 'Loop the Loop',
    intro: 'A LOOP repeats its moves. Loop DOWN, RIGHT to walk the steps.',
    grid: ['S   ', '*#  ', ' *# ', '  *E'],
    allowed: { dirs: ['D', 'R'], loops: true, functions: false, conditions: [], maxMain: 2 },
    parCommands: 1,
    solution: { main: [loop(3, D, R)], functions: [], conditions: [] },
  },
  {
    id: 'w3-02',
    world: 3,
    index: 2,
    name: 'Down the Stairs',
    intro: 'These steps head down and to the LEFT. Loop it four times.',
    grid: ['    S', '   #*', '  ## ', ' #*  ', 'E*   '],
    allowed: { dirs: ['D', 'L'], loops: true, functions: false, conditions: [], maxMain: 2 },
    parCommands: 1,
    solution: { main: [loop(4, D, L)], functions: [], conditions: [] },
  },
  {
    id: 'w3-03',
    world: 3,
    index: 3,
    name: 'Wide Steps',
    intro: 'Loop bodies can roll far. Each step here is a little wider.',
    grid: ['S      ', '*c#    ', '  *##  ', '    #*E'],
    allowed: { dirs: ['D', 'R'], loops: true, functions: false, conditions: [], maxMain: 2 },
    parCommands: 1,
    solution: { main: [loop(3, D, R)], functions: [], conditions: [] },
  },
  {
    id: 'w3-04',
    world: 3,
    index: 4,
    name: 'Enter the Canyon',
    intro: 'Add one command BEFORE the loop to line Bloop up first.',
    grid: ['S*#   ', '  #*  ', '   ## ', '    *E'],
    allowed: { dirs: ['R', 'D'], loops: true, functions: false, conditions: [], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, loop(3, D, R)], functions: [], conditions: [] },
  },
  {
    id: 'w3-05',
    world: 3,
    index: 5,
    name: 'Staircase Climb',
    intro: 'Loops can climb too! Repeat UP, RIGHT to reach the top.',
    grid: ['   #E', '  #* ', ' #*  ', '*#   ', 'S    '],
    allowed: { dirs: ['U', 'R'], loops: true, functions: false, conditions: [], maxMain: 2 },
    parCommands: 1,
    solution: { main: [loop(4, U, R)], functions: [], conditions: [] },
  },
  {
    id: 'w3-06',
    world: 3,
    index: 6,
    name: 'In and Out',
    intro: 'A command, then a loop, then a command. Loops fit in the middle.',
    grid: ['S*   ', ' #*  ', '  ## ', '   * ', '   E '],
    allowed: { dirs: ['R', 'D'], loops: true, functions: false, conditions: [], maxMain: 4 },
    parCommands: 3,
    solution: { main: [R, loop(2, D, R), D], functions: [], conditions: [] },
  },
  {
    id: 'w3-07',
    world: 3,
    index: 7,
    name: 'Deep Descent',
    intro: 'Way too long to type out — let the loop do the work five times.',
    grid: ['S     ', '*#    ', ' #*   ', '  ##  ', '   #* ', '    #E'],
    allowed: { dirs: ['D', 'R'], loops: true, functions: false, conditions: [], maxMain: 2 },
    parCommands: 1,
    solution: { main: [loop(5, D, R)], functions: [], conditions: [] },
  },
  {
    id: 'w3-08',
    world: 3,
    index: 8,
    name: 'Roll In, Then Loop',
    intro: 'Roll in with RIGHT, then loop the long staircase down.',
    grid: ['S*    ', ' c#   ', '  *#  ', '   ## ', '    *E'],
    allowed: { dirs: ['R', 'D'], loops: true, functions: false, conditions: [], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, loop(4, D, R)], functions: [], conditions: [] },
  },
  {
    id: 'w3-09',
    world: 3,
    index: 9,
    name: 'Serpentine',
    intro: 'A four-move loop snakes back and forth all the way down.',
    grid: ['S*#', '  #', '*##', '#  ', '##*', '  #', '##E'],
    allowed: { dirs: ['R', 'D', 'L'], loops: true, functions: false, conditions: [], maxMain: 2 },
    parCommands: 1,
    solution: { main: [loop(2, R, D, L, D)], functions: [], conditions: [] },
  },
  {
    id: 'w3-10',
    world: 3,
    index: 10,
    name: 'Climbing Snake',
    intro: 'Same snake, going up! Repeat RIGHT, UP, LEFT, UP.',
    grid: ['##E', '  #', '##*', '#  ', '*##', '  #', 'S*#'],
    allowed: { dirs: ['R', 'U', 'L'], loops: true, functions: false, conditions: [], maxMain: 2 },
    parCommands: 1,
    solution: { main: [loop(2, R, U, L, U)], functions: [], conditions: [] },
  },
  {
    id: 'w3-11',
    world: 3,
    index: 11,
    name: 'The Gauntlet',
    intro: 'Drop in, loop the steps, then roll out. Every token counts.',
    grid: ['S     ', '*     ', '#c    ', ' #*   ', '  ##  ', '   #*E'],
    allowed: { dirs: ['D', 'R'], loops: true, functions: false, conditions: [], maxMain: 4 },
    parCommands: 3,
    solution: { main: [D, loop(3, R, D), R], functions: [], conditions: [] },
  },
  {
    id: 'w3-12',
    world: 3,
    index: 12,
    name: 'Loopy Canyon Finale',
    intro: 'One roll-in and a five-time loop conquer the whole canyon.',
    grid: ['S*     ', ' ##    ', '  #*   ', '   ##  ', '    #* ', '     #E'],
    allowed: { dirs: ['R', 'D'], loops: true, functions: false, conditions: [], maxMain: 3 },
    parCommands: 2,
    solution: { main: [R, loop(5, D, R)], functions: [], conditions: [] },
  },
];
