// World 4 — Function Junction
// Introduces FUNCTION F1: define a reusable motif once, call it with {t:'call',f:0}.
// No loops, no conditions here — pure focus on spotting the repeated spatial motif.
const D = (d) => ({ t: 'dir', d });
const R = D('R'), L = D('L'), U = D('U'), Dn = D('D');
const C = { t: 'call', f: 0 };

export const levels = [
  {
    id: 'w4-01', world: 4, index: 1,
    name: 'Two of a Kind',
    intro: 'The path steps down twice the same way. Teach F1 the step, then call it twice!',
    grid: [
      'S*#    ',
      '  c    ',
      '  *##  ',
      '    *  ',
      '    E  ',
    ],
    allowed: { dirs: ['R', 'D'], loops: false, functions: true, conditions: [], maxMain: 4 },
    parCommands: 2,
    solution: { main: [C, C], functions: [[R, Dn]], conditions: [] },
  },
  {
    id: 'w4-02', world: 4, index: 2,
    name: 'Down the Line',
    intro: 'Down, then right — twice. One little function does both trips.',
    grid: [
      'S     ',
      'c     ',
      '*#*   ',
      '  c   ',
      '  *#E ',
    ],
    allowed: { dirs: ['D', 'R'], loops: false, functions: true, conditions: [], maxMain: 4 },
    parCommands: 2,
    solution: { main: [C, C], functions: [[Dn, R]], conditions: [] },
  },
  {
    id: 'w4-03', world: 4, index: 3,
    name: 'Triple Step',
    intro: 'Same staircase step, three times. Define it once, call it three times.',
    grid: [
      'S##      ',
      '  #      ',
      '  *#c    ',
      '    #    ',
      '    *#*  ',
      '      #  ',
      '      E  ',
    ],
    allowed: { dirs: ['R', 'D'], loops: false, functions: true, conditions: [], maxMain: 5 },
    parCommands: 3,
    solution: { main: [C, C, C], functions: [[R, Dn]], conditions: [] },
  },
  {
    id: 'w4-04', world: 4, index: 4,
    name: 'Waterfall',
    intro: 'Down then right, tumbling three levels. Let F1 do the falling.',
    grid: [
      'S      ',
      'c      ',
      '*##    ',
      '  c    ',
      '  *##  ',
      '    c  ',
      '    *#E',
    ],
    allowed: { dirs: ['D', 'R'], loops: false, functions: true, conditions: [], maxMain: 5 },
    parCommands: 3,
    solution: { main: [C, C, C], functions: [[Dn, R]], conditions: [] },
  },
  {
    id: 'w4-05', world: 4, index: 5,
    name: 'Zigzag Ridge',
    intro: 'The ridge snakes right, down, left, down — then repeats. Teach F1 the whole snake.',
    grid: [
      'S##c',
      '   #',
      '*###',
      '#   ',
      '#*##',
      '   #',
      '##*#',
      '#   ',
      'E###',
    ],
    allowed: { dirs: ['R', 'D', 'L'], loops: false, functions: true, conditions: [], maxMain: 3 },
    parCommands: 2,
    solution: { main: [C, C], functions: [[R, Dn, L, Dn]], conditions: [] },
  },
  {
    id: 'w4-06', world: 4, index: 6,
    name: 'Left Descent',
    intro: 'Start high on the right. Left, then down — three matching steps.',
    grid: [
      '    #*S',
      '    #  ',
      '  c#*  ',
      '  #    ',
      'c*#    ',
      '#      ',
      'E      ',
    ],
    allowed: { dirs: ['L', 'D'], loops: false, functions: true, conditions: [], maxMain: 4 },
    parCommands: 3,
    solution: { main: [C, C, C], functions: [[L, Dn]], conditions: [] },
  },
  {
    id: 'w4-07', world: 4, index: 7,
    name: 'Tight Squeeze',
    intro: 'Only 3 commands! Typing R,D six times will not fit — teach F1 the step.',
    grid: [
      'S##    ',
      '  #    ',
      '  *#c  ',
      '    #  ',
      '    *#*',
      '      #',
      '      E',
    ],
    allowed: { dirs: ['R', 'D'], loops: false, functions: true, conditions: [], maxMain: 3 },
    parCommands: 3,
    solution: { main: [C, C, C], functions: [[R, Dn]], conditions: [] },
  },
  {
    id: 'w4-08', world: 4, index: 8,
    name: 'Drop In',
    intro: 'One plain Down to enter, then two identical steps from your function.',
    grid: [
      'S      ',
      '#      ',
      '*#*    ',
      '  #    ',
      '  *#E  ',
    ],
    allowed: { dirs: ['R', 'D'], loops: false, functions: true, conditions: [], maxMain: 4 },
    parCommands: 3,
    solution: { main: [Dn, C, C], functions: [[R, Dn]], conditions: [] },
  },
  {
    id: 'w4-09', world: 4, index: 9,
    name: 'Summit Climb',
    intro: 'Climbing this time! Right then Up, three matching steps to the peak.',
    grid: [
      '      E  ',
      '      #  ',
      '    *#c  ',
      '    #    ',
      '  *#c    ',
      '  #      ',
      'S*#      ',
    ],
    allowed: { dirs: ['R', 'U'], loops: false, functions: true, conditions: [], maxMain: 4 },
    parCommands: 3,
    solution: { main: [C, C, C], functions: [[R, U]], conditions: [] },
  },
  {
    id: 'w4-10', world: 4, index: 10,
    name: 'Mirror Snake',
    intro: 'Only 2 commands. The snake weaves left, down, right, down — pack it into F1.',
    grid: [
      '*##S',
      '#   ',
      '###*',
      '   #',
      '####',
      '#   ',
      '*###',
      '   #',
      '###E',
    ],
    allowed: { dirs: ['L', 'D', 'R'], loops: false, functions: true, conditions: [], maxMain: 2 },
    parCommands: 2,
    solution: { main: [C, C], functions: [[L, Dn, R, Dn]], conditions: [] },
  },
  {
    id: 'w4-11', world: 4, index: 11,
    name: 'Long Cascade',
    intro: 'Four identical steps down the mountain. One function, four calls.',
    grid: [
      'S##      ',
      '  #      ',
      '  *#c    ',
      '    #    ',
      '    *#c  ',
      '      #  ',
      '      *#c',
      '        #',
      '        E',
    ],
    allowed: { dirs: ['R', 'D'], loops: false, functions: true, conditions: [], maxMain: 5 },
    parCommands: 4,
    solution: { main: [C, C, C, C], functions: [[R, Dn]], conditions: [] },
  },
  {
    id: 'w4-12', world: 4, index: 12,
    name: 'Grand Staircase',
    intro: 'Three wide steps, only 3 commands. The function is the only way down.',
    grid: [
      'S##c      ',
      '   #      ',
      '   *##c   ',
      '      #   ',
      '      *##*',
      '         #',
      '         E',
    ],
    allowed: { dirs: ['R', 'D'], loops: false, functions: true, conditions: [], maxMain: 3 },
    parCommands: 3,
    solution: { main: [C, C, C], functions: [[R, Dn]], conditions: [] },
  },
];
